// This file was auto generated by prisma-kysely, do not edit.
import type { ColumnType } from "kysely";
export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
export type Timestamp = ColumnType<Date, Date | string, Date | string>;

import type { ServiceRewardsActorParameterType } from "./enums";

export type application_config = {
    id: Generated<number>;
    activation_epoch: string;
    epochs_per_quarter: string;
};
export type filecoin_pay_contract = {
    contract_address: string;
    admittance_epoch: string;
    admittance_log_index: number;
    admittance_tx_hash: string;
    removal_epoch: string | null;
    removal_log_index: number | null;
    removal_tx_hash: string | null;
};
export type filecoin_pay_fee_auction = {
    id: Generated<string>;
    filecoin_pay_contract_address: string;
    tx_hash: string;
    log_index: number;
    amount_actual: string;
    fil_burned: string;
    token_address: string;
    auctioned_at_epoch: string;
};
export type filecoin_pay_payment = {
    id: Generated<string>;
    filecoin_pay_contract_address: string;
    tx_hash: string;
    log_index: number;
    net_payee_amount: string;
    network_fee: string;
    one_time: boolean;
    operator_commission: string;
    rail_id: string;
    settled_at_epoch: string;
    total_amount: string;
};
export type filecoin_pay_rail = {
    filecoin_pay_contract_address: string;
    tx_hash: string;
    log_index: number;
    operator: string;
    rail_id: string;
    token: string;
    validator: string;
    payee: string;
    payer: string;
};
export type indexer_state = {
    contract_address: string;
    end_block: string;
    last_run_date: Timestamp;
    version: number;
};
export type qualified_price_periods_mv = {
    quarter_num: number;
    epoch: string;
    log_index: number;
    lot_atto_usd: string;
    claim_atto_fil: string;
    claim_tx_hash: string;
};
export type quarter_bound_volume = {
    quarter_num: number;
    volume_atto_usd: string;
    epoch: string;
    tx_hash: string;
};
export type service_orchestrator = {
    id: string;
};
export type service_orchestrator_admission = {
    service_orchestrator_id: string;
    wallet: string;
    admission_epoch: string;
    admission_log_index: number;
    admission_tx_hash: string;
    removal_epoch: string | null;
    removal_log_index: number | null;
    removal_tx_hash: string | null;
};
export type service_orchestrator_quarterly_volume = {
    service_orchestrator_id: string;
    quarter_num: number;
    volume_atto_usd: string;
    is_correction: boolean;
    posting_epoch: string;
    posting_log_index: number;
    posting_tx_hash: string;
};
export type service_pair = {
    service_orchestrator_id: string;
    payer: string;
    operator: string;
    from_epoch: string;
    from_log_index: number;
    to_epoch: string | null;
    to_log_index: number | null;
    binding_epoch: string;
    binding_tx_hash: string;
    unbinding_epoch: string | null;
    unbinding_tx_hash: string | null;
};
export type service_rewards_actor_parameter = {
    parameter_type: ServiceRewardsActorParameterType;
    parameter_value: string;
    update_epoch: string;
    update_log_index: number;
    update_tx_hash: string;
};
export type whitelisted_token = {
    token_address: string;
    token_decimals: number;
    token_symbol: string;
    admittance_epoch: string;
    admittance_log_index: number;
    admittance_tx_hash: string;
    removal_epoch: string | null;
    removal_log_index: number | null;
    removal_tx_hash: string | null;
};
export type DB = {
    application_config: application_config;
    filecoin_pay_contract: filecoin_pay_contract;
    filecoin_pay_fee_auction: filecoin_pay_fee_auction;
    filecoin_pay_payment: filecoin_pay_payment;
    filecoin_pay_rail: filecoin_pay_rail;
    indexer_state: indexer_state;
    qualified_price_periods_mv: qualified_price_periods_mv;
    quarter_bound_volume: quarter_bound_volume;
    service_orchestrator: service_orchestrator;
    service_orchestrator_admission: service_orchestrator_admission;
    service_orchestrator_quarterly_volume: service_orchestrator_quarterly_volume;
    service_pair: service_pair;
    service_rewards_actor_parameter: service_rewards_actor_parameter;
    whitelisted_token: whitelisted_token;
};
